- name: Deploy to Server
  uses: appleboy/ssh-action@v1.0.0
  with:
    host: ${{ secrets.SERVER_HOST }}
    username: ${{ secrets.SERVER_USER }}
    key: |
      ${{ secrets.SERVER_SSH_KEY_BASE64 }} | base64 --decode
    port: 22
    script: |
      cd /var/www/designPattern
      git pull origin main
